name: miscelaneos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  permission_handler: ^12.0.1
  sensors_plus: ^6.1.1
  share_plus: ^11.0.0
  local_auth: ^2.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
    - .env
